baseurl = "http://paul-james.me"
relativeurls = true
languageCode = "en-us"
title = "Paul James' Rando Analytics Blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "pjames R-pkg"
    url = "/pjames/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Paul-James"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/PaulJames379"


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
